### ISSUE TITLE
Can u change Daemon capital under DEXes into Maladex?

### ISSUE THREAD

**Issue by Eclip7e** [input-output-hk/essential-cardano#112]
We changed name from daemon -> Maladex, could u update list? Thank you in advance

**Comment by nahern** [comment]
sure, no problem. We'll get that updated for you. Thanks for letting us know!

**Comment by nahern** [comment]
is this your new website? https://maladex.com/

**Comment by Eclip7e** [comment]
Yes sir ;)

**Comment by nahern** [comment]
updated for you.
