### ISSUE TITLE
Rationale for having two separate lists ?

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/essential-cardano#13]
Before anything: great initiative, I've been hoping for such a list for a long time.  

I find the structure of the repository and the wording however a bit confusing. The README (and most announcements) mention **one** list, whereas there really are two lists:

- https://github.com/input-output-hk/essential-cardano/blob/main/essential-cardano-list.md
- https://github.com/input-output-hk/essential-cardano/blob/main/resources.md

I was surprised at first to not find some specific projects in the "essential list", only later to notice that there was a second link and second list with much more resources for developers. I think [some others](https://github.com/input-output-hk/essential-cardano/pull/7) may also have been confused by that (cc @mmahut, Blockfrost already is in the second list). 

Even after re-reading the README and both lists, I am still not quite sure about what should go into one list or the other? May I suggest to merge both lists into one or, structure the main list into categories and multiple sub-lists as some large "awesome XXX" lists sometimes do. 

cc @nahern

**Comment by 7robbie5** [comment]
You are right. It looks like two indeed. The used it at one page and have the original file too. They simply should put everything on the first page. Or at least the old school directory with categories, links as entry. People, haha I mean myself, want to have a quick overview, useful also for on the go. Just an idea.

**Comment by nahern** [comment]
thank you Matthias and 7robbie5, I started it as one list, then thought it better to split out resources specifically, but I take your point and have merged this all back into the one list, so there is a full overview. I thought it would be too much scrolling, but we certainly don't want confusion and people missing out on the dev resources etc. 

Thanks for this point and glad you like it!
