### ISSUE TITLE
Order lists in alphabetical order

### ISSUE THREAD

**Issue by wout** [input-output-hk/essential-cardano#146]
As it is right now, the lists are quite messy. What about ordering them alphabetically?

I don't mind creating another PR for that, but I thought I'd ask first because there may be some logic behind the current order.

**Comment by nahern** [comment]
am working on that, but it is time consuming, almost there! thanks for your feedback.

**Comment by wout** [comment]
Ok, great! Just FYI, in Sublime Text it's a built-in feature to order lists with a click of a button. :slightly_smiling_face:
