### ISSUE TITLE
Suggestion: list of IOHK papers

### ISSUE THREAD

**Issue by wei3hua2** [input-output-hk/essential-cardano#17]
I created a scraper previously to download and categorizes IOHK papers by years, tags, types, and authors.

[awesome-iohk-papers](https://github.com/wei3hua2/awesome-iohk-papers.git)

Depend on if it makes sense for this project, I can submit a PR to merge the generated markdowns to this project.

**Comment by nahern** [comment]
good idea, I did think about this, so I think we should add the papers. Will take a look at that link, thank you.

**Comment by wei3hua2** [comment]
It seems a little redundant to think of it. Thanks.
