### ISSUE TITLE
Add community video links

### ISSUE THREAD

**Issue by whitevo** [input-output-hk/essential-cardano#202]
📹 Community Videos 📹
Catalyst Swarm Youtube: https://www.youtube.com/channel/UCuXdR8JMH0QriU0uOTVpg3w
Catalyst School Youtube: https://www.youtube.com/channel/UCIPvRvMoxhmHLUuPPcsMmmg

Not sure if they are relevant, but these are homepage website links
Catalyst Swarm Website: https://catalystswarm.com/
Catalyst School Website: https://thecatalyst.school/

**Comment by nahern** [comment]
thank you, can you close this issue and raise a PR with where you want them included and I will approve, thanks.

**Comment by whitevo** [comment]
The list is in this file:
https://github.com/input-output-hk/essential-cardano/blob/main/essential-cardano-list.md

**Comment by nahern** [comment]
these have both been added to the Catalyst section, thank you
