### ISSUE TITLE
Please update essential-cardano-list.md

### ISSUE THREAD

**Issue by ElliotAda** [input-output-hk/essential-cardano#223]
Can you please add (https://thothus.io/) under DEXs

**Comment by nahern** [comment]
can you please raise a PR for this inclusion and please provide us with the logo, some profiles of the main individuals involved and a URL to the site. Also if you have a blurb explaining your project and/or whitepaper/specification that would be great. Thank you!

**Comment by nahern** [comment]
added, thank you.
