### ISSUE TITLE
There must be a Quality Assessment for projects on this "essential" list!

### ISSUE THREAD

**Issue by domib97** [input-output-hk/essential-cardano#238]
As pointed out here: https://github.com/input-output-hk/essential-cardano/issues/164 there is little to none due diligence done for the projects that want to be added to this list. 

The evidence that a lack of QA will harm people that blindly accept this list is shown here: https://github.com/input-output-hk/essential-cardano/pull/233 , where a evidently Scam project made its way to this list.

I worry about people getting scammed by a lack of QA especially when the new Essential Cardano website is coming online soon.

**Comment by nahern** [comment]
we have a due diligence process already in place.

**Comment by domib97** [comment]
A disgrace for IOG!
